### ISSUE TITLE
Add RF keywords "Is Pin High" and "Is Pin Low"

### ISSUE THREAD

**Issue by yusufcanb** [yusufcanb/robotframework-gpio#1]

**Comment by adrianyorke** [comment]
Happy to help with this one - just need to wire up a LED and breadboard for my test Pi.

Planning updates to:

- GPIOLibrary/keywords/GPIOKeywords.py
- atests/gpio.robot
- README

**Comment by yusufcanb** [comment]
Thank you. 
Since Github Pages enabled for [(library documentation)](https://yusufcanb.github.io/robotframework-gpio/) , we can also update documentation file `/docs/index.html` using `robot.libdoc`.
